# Generated by Django 2.2.17 on 2020-12-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identification',
            name='id_card_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/img_card/'),
        ),
        migrations.AlterField(
            model_name='identification',
            name='selfie_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/img_selfie/'),
        ),
    ]
